

var data = [
    {
        "City": "albany",
        "Country": "US",
        "City ID": "19530.0",
        "Latitude": "42.6",
        "Longitude": "-73.97",
        "Temperature (F)": "81.0",
        "Humidity (%)": "39.0",
        "Cloudiness (%)": "62.0",
        "Wind Speed (mph)": "10.74"
    },
    {
        "City": "loviisa",
        "Country": "FI",
        "City ID": "2004269.0",
        "Latitude": "60.46",
        "Longitude": "26.23",
        "Temperature (F)": "72.0",
        "Humidity (%)": "60.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "1.01"
    },
    {
        "City": "aklavik",
        "Country": "CA",
        "City ID": "821.0",
        "Latitude": "68.22",
        "Longitude": "-135.01",
        "Temperature (F)": "51.8",
        "Humidity (%)": "57.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "9.17"
    },
    {
        "City": "tuktoyaktuk",
        "Country": "CA",
        "City ID": "942.0",
        "Latitude": "69.45",
        "Longitude": "-133.04",
        "Temperature (F)": "37.4",
        "Humidity (%)": "93.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "9.17"
    },
    {
        "City": "hermanus",
        "Country": "ZA",
        "City ID": "2003650.0",
        "Latitude": "-34.42",
        "Longitude": "19.23",
        "Temperature (F)": "54.0",
        "Humidity (%)": "81.0",
        "Cloudiness (%)": "6.0",
        "Wind Speed (mph)": "7.0"
    },
    {
        "City": "mataura",
        "Country": "NZ",
        "City ID": "2008959.0",
        "Latitude": "-46.19",
        "Longitude": "168.86",
        "Temperature (F)": "39.0",
        "Humidity (%)": "83.0",
        "Cloudiness (%)": "79.0",
        "Wind Speed (mph)": "3.0"
    },
    {
        "City": "new norfolk",
        "Country": "AU",
        "City ID": "2031307.0",
        "Latitude": "-42.78",
        "Longitude": "147.06",
        "Temperature (F)": "39.99",
        "Humidity (%)": "84.0",
        "Cloudiness (%)": "56.0",
        "Wind Speed (mph)": "3.04"
    },
    {
        "City": "champerico",
        "Country": "GT",
        "City ID": "7068.0",
        "Latitude": "14.3",
        "Longitude": "-91.92",
        "Temperature (F)": "89.6",
        "Humidity (%)": "59.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "yulara",
        "Country": "AU",
        "City ID": "9487.0",
        "Latitude": "-25.24",
        "Longitude": "130.99",
        "Temperature (F)": "42.8",
        "Humidity (%)": "60.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "5.82"
    },
    {
        "City": "tautira",
        "Country": "PF",
        "City ID": "7318.0",
        "Latitude": "-17.73",
        "Longitude": "-149.15",
        "Temperature (F)": "78.8",
        "Humidity (%)": "69.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "11.41"
    },
    {
        "City": "nome",
        "Country": "US",
        "City ID": "7770.0",
        "Latitude": "64.5",
        "Longitude": "-165.41",
        "Temperature (F)": "46.4",
        "Humidity (%)": "65.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "14.99"
    },
    {
        "City": "neuquen",
        "Country": "AR",
        "City ID": "8310.0",
        "Latitude": "-38.95",
        "Longitude": "-68.06",
        "Temperature (F)": "33.8",
        "Humidity (%)": "80.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "9.17"
    },
    {
        "City": "geraldton",
        "Country": "AU",
        "City ID": "9522.0",
        "Latitude": "-28.77",
        "Longitude": "114.6",
        "Temperature (F)": "57.2",
        "Humidity (%)": "87.0",
        "Cloudiness (%)": "7.0",
        "Wind Speed (mph)": "12.75"
    },
    {
        "City": "san cristobal",
        "Country": "VE",
        "City ID": "8587.0",
        "Latitude": "7.77",
        "Longitude": "-72.22",
        "Temperature (F)": "89.6",
        "Humidity (%)": "49.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "24.16"
    },
    {
        "City": "jamestown",
        "Country": "US",
        "City ID": "4588.0",
        "Latitude": "42.1",
        "Longitude": "-79.24",
        "Temperature (F)": "78.01",
        "Humidity (%)": "44.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "arya",
        "Country": "PK",
        "City ID": "9721.0",
        "Latitude": "33.6",
        "Longitude": "73.07",
        "Temperature (F)": "82.4",
        "Humidity (%)": "65.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "9.17"
    },
    {
        "City": "busselton",
        "Country": "AU",
        "City ID": "2011706.0",
        "Latitude": "-33.65",
        "Longitude": "115.33",
        "Temperature (F)": "57.0",
        "Humidity (%)": "87.0",
        "Cloudiness (%)": "37.0",
        "Wind Speed (mph)": "11.07"
    },
    {
        "City": "sale",
        "Country": "MA",
        "City ID": "2402.0",
        "Latitude": "34.04",
        "Longitude": "-6.82",
        "Temperature (F)": "71.6",
        "Humidity (%)": "68.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "9.17"
    },
    {
        "City": "peniche",
        "Country": "PT",
        "City ID": "2002665.0",
        "Latitude": "39.36",
        "Longitude": "-9.38",
        "Temperature (F)": "71.01",
        "Humidity (%)": "72.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "10.0"
    },
    {
        "City": "ushuaia",
        "Country": "AR",
        "City ID": "8303.0",
        "Latitude": "-54.8",
        "Longitude": "-68.3",
        "Temperature (F)": "37.4",
        "Humidity (%)": "69.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "24.16"
    },
    {
        "City": "payson",
        "Country": "US",
        "City ID": "5442.0",
        "Latitude": "40.04",
        "Longitude": "-111.73",
        "Temperature (F)": "77.0",
        "Humidity (%)": "36.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "vaini",
        "Country": "TO",
        "City ID": "7285.0",
        "Latitude": "-21.2",
        "Longitude": "-175.2",
        "Temperature (F)": "71.6",
        "Humidity (%)": "94.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "5.82"
    },
    {
        "City": "saint-philippe",
        "Country": "RE",
        "City ID": "2127.0",
        "Latitude": "-21.36",
        "Longitude": "55.77",
        "Temperature (F)": "71.6",
        "Humidity (%)": "73.0",
        "Cloudiness (%)": "62.0",
        "Wind Speed (mph)": "20.8"
    },
    {
        "City": "mali",
        "Country": "GN",
        "City ID": "2433.0",
        "Latitude": "12.08",
        "Longitude": "-12.3",
        "Temperature (F)": "95.0",
        "Humidity (%)": "59.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "quatre cocos",
        "Country": "MU",
        "City ID": "2061.0",
        "Latitude": "-20.21",
        "Longitude": "57.76",
        "Temperature (F)": "73.0",
        "Humidity (%)": "83.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "17.22"
    },
    {
        "City": "kenai",
        "Country": "US",
        "City ID": "7680.0",
        "Latitude": "60.55",
        "Longitude": "-151.26",
        "Temperature (F)": "59.0",
        "Humidity (%)": "66.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "callaway",
        "Country": "US",
        "City ID": "5308.0",
        "Latitude": "30.15",
        "Longitude": "-85.57",
        "Temperature (F)": "93.2",
        "Humidity (%)": "59.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "alexandria",
        "Country": "EG",
        "City ID": "2511.0",
        "Latitude": "31.22",
        "Longitude": "29.96",
        "Temperature (F)": "77.0",
        "Humidity (%)": "78.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "9.17"
    },
    {
        "City": "north bend",
        "Country": "US",
        "City ID": "5239.0",
        "Latitude": "43.41",
        "Longitude": "-124.22",
        "Temperature (F)": "75.99",
        "Humidity (%)": "72.0",
        "Cloudiness (%)": "1.0",
        "Wind Speed (mph)": "13.87"
    },
    {
        "City": "avarua",
        "Country": "CK",
        "City ID": "7271.0",
        "Latitude": "-21.21",
        "Longitude": "-159.78",
        "Temperature (F)": "71.6",
        "Humidity (%)": "73.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "3.36"
    },
    {
        "City": "hobart",
        "Country": "AU",
        "City ID": "9545.0",
        "Latitude": "-42.88",
        "Longitude": "147.33",
        "Temperature (F)": "39.99",
        "Humidity (%)": "86.0",
        "Cloudiness (%)": "52.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "saint-georges",
        "Country": "GD",
        "City ID": "8781.0",
        "Latitude": "12.06",
        "Longitude": "-61.75",
        "Temperature (F)": "87.8",
        "Humidity (%)": "70.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "17.22"
    },
    {
        "City": "clyde",
        "Country": "US",
        "City ID": "2016547.0",
        "Latitude": "41.3",
        "Longitude": "-82.98",
        "Temperature (F)": "86.0",
        "Humidity (%)": "35.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "4.0"
    },
    {
        "City": "wilmington",
        "Country": "US",
        "City ID": "4521.0",
        "Latitude": "34.23",
        "Longitude": "-77.94",
        "Temperature (F)": "91.0",
        "Humidity (%)": "38.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "2.44"
    },
    {
        "City": "sitka",
        "Country": "US",
        "City ID": "7795.0",
        "Latitude": "57.05",
        "Longitude": "-135.33",
        "Temperature (F)": "53.6",
        "Humidity (%)": "87.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "nikolskoye",
        "Country": "RU",
        "City ID": "8926.0",
        "Latitude": "59.7",
        "Longitude": "30.79",
        "Temperature (F)": "77.0",
        "Humidity (%)": "47.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "6.71"
    },
    {
        "City": "kapaa",
        "Country": "US",
        "City ID": "7873.0",
        "Latitude": "22.08",
        "Longitude": "-159.32",
        "Temperature (F)": "80.6",
        "Humidity (%)": "74.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "9.17"
    },
    {
        "City": "victoria",
        "Country": "HK",
        "City ID": "265999.0",
        "Latitude": "22.29",
        "Longitude": "114.16",
        "Temperature (F)": "82.99",
        "Humidity (%)": "81.0",
        "Cloudiness (%)": "74.0",
        "Wind Speed (mph)": "3.0"
    },
    {
        "City": "port alfred",
        "Country": "ZA",
        "City ID": "2011314.0",
        "Latitude": "-33.59",
        "Longitude": "26.89",
        "Temperature (F)": "59.0",
        "Humidity (%)": "70.0",
        "Cloudiness (%)": "7.0",
        "Wind Speed (mph)": "5.01"
    },
    {
        "City": "yellowknife",
        "Country": "CA",
        "City ID": "1007.0",
        "Latitude": "62.46",
        "Longitude": "-114.35",
        "Temperature (F)": "64.99",
        "Humidity (%)": "55.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "3.36"
    },
    {
        "City": "pitimbu",
        "Country": "BR",
        "City ID": "8391.0",
        "Latitude": "-7.47",
        "Longitude": "-34.81",
        "Temperature (F)": "80.6",
        "Humidity (%)": "78.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "11.41"
    },
    {
        "City": "georgetown",
        "Country": "MY",
        "City ID": "9429.0",
        "Latitude": "5.41",
        "Longitude": "100.34",
        "Temperature (F)": "80.6",
        "Humidity (%)": "88.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "2.24"
    },
    {
        "City": "hilo",
        "Country": "US",
        "City ID": "7881.0",
        "Latitude": "19.73",
        "Longitude": "-155.09",
        "Temperature (F)": "78.8",
        "Humidity (%)": "65.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "4.65"
    },
    {
        "City": "prince rupert",
        "Country": "CA",
        "City ID": "883.0",
        "Latitude": "54.32",
        "Longitude": "-130.32",
        "Temperature (F)": "55.4",
        "Humidity (%)": "87.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "9.17"
    },
    {
        "City": "witu",
        "Country": "KE",
        "City ID": "5604.0",
        "Latitude": "-2.39",
        "Longitude": "40.44",
        "Temperature (F)": "78.8",
        "Humidity (%)": "78.0",
        "Cloudiness (%)": "1.0",
        "Wind Speed (mph)": "12.84"
    },
    {
        "City": "tasiilaq",
        "Country": "GL",
        "City ID": "81.0",
        "Latitude": "65.61",
        "Longitude": "-37.64",
        "Temperature (F)": "46.4",
        "Humidity (%)": "75.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "8.05"
    },
    {
        "City": "methven",
        "Country": "NZ",
        "City ID": "20126.0",
        "Latitude": "-43.63",
        "Longitude": "171.65",
        "Temperature (F)": "45.0",
        "Humidity (%)": "91.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "1.01"
    },
    {
        "City": "rorvik",
        "Country": "NO",
        "City ID": "1653.0",
        "Latitude": "64.86",
        "Longitude": "11.24",
        "Temperature (F)": "62.6",
        "Humidity (%)": "67.0",
        "Cloudiness (%)": "22.0",
        "Wind Speed (mph)": "17.22"
    },
    {
        "City": "arroyo",
        "Country": "ES",
        "City ID": "6437.0",
        "Latitude": "41.61",
        "Longitude": "-4.8",
        "Temperature (F)": "78.01",
        "Humidity (%)": "33.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "14.99"
    },
    {
        "City": "ponta do sol",
        "Country": "PT",
        "City ID": "6894.0",
        "Latitude": "32.67",
        "Longitude": "-17.1",
        "Temperature (F)": "71.6",
        "Humidity (%)": "64.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "13.87"
    },
    {
        "City": "narrabri",
        "Country": "AU",
        "City ID": "9563.0",
        "Latitude": "-30.32",
        "Longitude": "149.78",
        "Temperature (F)": "41.0",
        "Humidity (%)": "86.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "1.12"
    },
    {
        "City": "fortuna",
        "Country": "US",
        "City ID": "4127.0",
        "Latitude": "40.6",
        "Longitude": "-124.16",
        "Temperature (F)": "64.0",
        "Humidity (%)": "88.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "9.17"
    },
    {
        "City": "maldonado",
        "Country": "UY",
        "City ID": "8712.0",
        "Latitude": "-34.67",
        "Longitude": "-54.92",
        "Temperature (F)": "55.0",
        "Humidity (%)": "62.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "19.46"
    },
    {
        "City": "port elizabeth",
        "Country": "ZA",
        "City ID": "1973.0",
        "Latitude": "-33.92",
        "Longitude": "25.57",
        "Temperature (F)": "59.0",
        "Humidity (%)": "62.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "18.34"
    },
    {
        "City": "meadow lake",
        "Country": "US",
        "City ID": "3205.0",
        "Latitude": "34.8",
        "Longitude": "-106.54",
        "Temperature (F)": "91.99",
        "Humidity (%)": "18.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "6.55"
    },
    {
        "City": "mar del plata",
        "Country": "AR",
        "City ID": "8305.0",
        "Latitude": "-38.0",
        "Longitude": "-57.56",
        "Temperature (F)": "52.0",
        "Humidity (%)": "66.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "13.87"
    },
    {
        "City": "manado",
        "Country": "ID",
        "City ID": "9356.0",
        "Latitude": "1.49",
        "Longitude": "124.85",
        "Temperature (F)": "75.2",
        "Humidity (%)": "100.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "4.21"
    },
    {
        "City": "aykhal",
        "Country": "RU",
        "City ID": "8846.0",
        "Latitude": "66.0",
        "Longitude": "111.5",
        "Temperature (F)": "60.8",
        "Humidity (%)": "59.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "6.71"
    },
    {
        "City": "erfurt",
        "Country": "DE",
        "City ID": "1266.0",
        "Latitude": "50.98",
        "Longitude": "11.03",
        "Temperature (F)": "79.0",
        "Humidity (%)": "53.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "2.24"
    },
    {
        "City": "whitianga",
        "Country": "NZ",
        "City ID": "2002961.0",
        "Latitude": "-36.83",
        "Longitude": "175.7",
        "Temperature (F)": "57.99",
        "Humidity (%)": "98.0",
        "Cloudiness (%)": "83.0",
        "Wind Speed (mph)": "7.0"
    },
    {
        "City": "talcahuano",
        "Country": "CL",
        "City ID": "8499.0",
        "Latitude": "-36.72",
        "Longitude": "-73.12",
        "Temperature (F)": "51.8",
        "Humidity (%)": "93.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "12.75"
    },
    {
        "City": "palm harbor",
        "Country": "US",
        "City ID": "3654.0",
        "Latitude": "28.08",
        "Longitude": "-82.76",
        "Temperature (F)": "99.0",
        "Humidity (%)": "47.0",
        "Cloudiness (%)": "1.0",
        "Wind Speed (mph)": "5.82"
    },
    {
        "City": "iqaluit",
        "Country": "CA",
        "City ID": "797.0",
        "Latitude": "63.75",
        "Longitude": "-68.51",
        "Temperature (F)": "48.2",
        "Humidity (%)": "70.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "2.24"
    },
    {
        "City": "iisalmi",
        "Country": "FI",
        "City ID": "1345.0",
        "Latitude": "63.56",
        "Longitude": "27.19",
        "Temperature (F)": "77.0",
        "Humidity (%)": "47.0",
        "Cloudiness (%)": "49.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "klaksvik",
        "Country": "FO",
        "City ID": "1596.0",
        "Latitude": "62.23",
        "Longitude": "-6.59",
        "Temperature (F)": "53.6",
        "Humidity (%)": "100.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "bambous virieux",
        "Country": "MU",
        "City ID": "2061.0",
        "Latitude": "-20.34",
        "Longitude": "57.76",
        "Temperature (F)": "73.0",
        "Humidity (%)": "83.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "17.22"
    },
    {
        "City": "uberaba",
        "Country": "BR",
        "City ID": "8472.0",
        "Latitude": "-19.75",
        "Longitude": "-47.93",
        "Temperature (F)": "78.8",
        "Humidity (%)": "36.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "5.82"
    },
    {
        "City": "pierre",
        "Country": "US",
        "City ID": "5361.0",
        "Latitude": "44.37",
        "Longitude": "-100.35",
        "Temperature (F)": "81.0",
        "Humidity (%)": "54.0",
        "Cloudiness (%)": "1.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "cabo san lucas",
        "Country": "MX",
        "City ID": "7151.0",
        "Latitude": "22.89",
        "Longitude": "-109.91",
        "Temperature (F)": "89.6",
        "Humidity (%)": "15.0",
        "Cloudiness (%)": "5.0",
        "Wind Speed (mph)": "6.76"
    },
    {
        "City": "florianopolis",
        "Country": "BR",
        "City ID": "8360.0",
        "Latitude": "-27.61",
        "Longitude": "-48.5",
        "Temperature (F)": "64.0",
        "Humidity (%)": "42.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "12.75"
    },
    {
        "City": "cayenne",
        "Country": "GF",
        "City ID": "8669.0",
        "Latitude": "4.93",
        "Longitude": "-52.33",
        "Temperature (F)": "84.2",
        "Humidity (%)": "74.0",
        "Cloudiness (%)": "98.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "bluff",
        "Country": "NZ",
        "City ID": "2008959.0",
        "Latitude": "-46.6",
        "Longitude": "168.33",
        "Temperature (F)": "39.0",
        "Humidity (%)": "83.0",
        "Cloudiness (%)": "99.0",
        "Wind Speed (mph)": "3.0"
    },
    {
        "City": "antofagasta",
        "Country": "CL",
        "City ID": "8488.0",
        "Latitude": "-23.65",
        "Longitude": "-70.4",
        "Temperature (F)": "62.6",
        "Humidity (%)": "63.0",
        "Cloudiness (%)": "22.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "bethel",
        "Country": "US",
        "City ID": "3888.0",
        "Latitude": "41.37",
        "Longitude": "-73.41",
        "Temperature (F)": "84.0",
        "Humidity (%)": "39.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "5.82"
    },
    {
        "City": "talnakh",
        "Country": "RU",
        "City ID": "8951.0",
        "Latitude": "69.49",
        "Longitude": "88.4",
        "Temperature (F)": "62.6",
        "Humidity (%)": "63.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "6.71"
    },
    {
        "City": "porto nacional",
        "Country": "BR",
        "City ID": "8419.0",
        "Latitude": "-10.71",
        "Longitude": "-48.42",
        "Temperature (F)": "91.0",
        "Humidity (%)": "43.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "8.05"
    },
    {
        "City": "bairiki",
        "Country": "KI",
        "City ID": "7300.0",
        "Latitude": "1.33",
        "Longitude": "172.98",
        "Temperature (F)": "82.4",
        "Humidity (%)": "74.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "11.41"
    },
    {
        "City": "severomorsk",
        "Country": "RU",
        "City ID": "8927.0",
        "Latitude": "69.07",
        "Longitude": "33.42",
        "Temperature (F)": "53.6",
        "Humidity (%)": "66.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "8.95"
    },
    {
        "City": "santa marta",
        "Country": "CO",
        "City ID": "8624.0",
        "Latitude": "11.24",
        "Longitude": "-74.2",
        "Temperature (F)": "91.4",
        "Humidity (%)": "63.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "8.05"
    },
    {
        "City": "saldanha",
        "Country": "ZA",
        "City ID": "1943.0",
        "Latitude": "-33.01",
        "Longitude": "17.94",
        "Temperature (F)": "55.4",
        "Humidity (%)": "87.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "lompoc",
        "Country": "US",
        "City ID": "4747.0",
        "Latitude": "34.64",
        "Longitude": "-120.46",
        "Temperature (F)": "69.01",
        "Humidity (%)": "77.0",
        "Cloudiness (%)": "9.0",
        "Wind Speed (mph)": "8.05"
    },
    {
        "City": "falun",
        "Country": "SE",
        "City ID": "1789.0",
        "Latitude": "60.6",
        "Longitude": "15.63",
        "Temperature (F)": "82.4",
        "Humidity (%)": "39.0",
        "Cloudiness (%)": "69.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "punta arenas",
        "Country": "CL",
        "City ID": "8487.0",
        "Latitude": "-53.15",
        "Longitude": "-70.92",
        "Temperature (F)": "37.4",
        "Humidity (%)": "69.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "11.41"
    },
    {
        "City": "clyde river",
        "Country": "CA",
        "City ID": "776.0",
        "Latitude": "70.47",
        "Longitude": "-68.59",
        "Temperature (F)": "48.2",
        "Humidity (%)": "87.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "puerto baquerizo moreno",
        "Country": "EC",
        "City ID": "8546.0",
        "Latitude": "-0.9",
        "Longitude": "-89.6",
        "Temperature (F)": "77.0",
        "Humidity (%)": "73.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "18.34"
    },
    {
        "City": "kahului",
        "Country": "US",
        "City ID": "7879.0",
        "Latitude": "20.89",
        "Longitude": "-156.47",
        "Temperature (F)": "82.4",
        "Humidity (%)": "61.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "17.22"
    },
    {
        "City": "vangazi",
        "Country": "LV",
        "City ID": "1876.0",
        "Latitude": "57.09",
        "Longitude": "24.55",
        "Temperature (F)": "80.6",
        "Humidity (%)": "44.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "arraial do cabo",
        "Country": "BR",
        "City ID": "8326.0",
        "Latitude": "-22.97",
        "Longitude": "-42.03",
        "Temperature (F)": "78.8",
        "Humidity (%)": "73.0",
        "Cloudiness (%)": "7.0",
        "Wind Speed (mph)": "12.75"
    },
    {
        "City": "saint-louis",
        "Country": "SN",
        "City ID": "2427.0",
        "Latitude": "16.33",
        "Longitude": "-15.0",
        "Temperature (F)": "102.2",
        "Humidity (%)": "31.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "2.24"
    },
    {
        "City": "nishihara",
        "Country": "JP",
        "City ID": "8156.0",
        "Latitude": "26.18",
        "Longitude": "127.76",
        "Temperature (F)": "75.2",
        "Humidity (%)": "100.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "3.36"
    },
    {
        "City": "new port richey",
        "Country": "US",
        "City ID": "2012526.0",
        "Latitude": "28.24",
        "Longitude": "-82.72",
        "Temperature (F)": "98.01",
        "Humidity (%)": "47.0",
        "Cloudiness (%)": "33.0",
        "Wind Speed (mph)": "1.99"
    },
    {
        "City": "barrow",
        "Country": "US",
        "City ID": "7649.0",
        "Latitude": "71.29",
        "Longitude": "-156.79",
        "Temperature (F)": "42.8",
        "Humidity (%)": "87.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "9.17"
    },
    {
        "City": "anadyr",
        "Country": "RU",
        "City ID": "8872.0",
        "Latitude": "64.75",
        "Longitude": "177.48",
        "Temperature (F)": "41.0",
        "Humidity (%)": "69.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "29.08"
    },
    {
        "City": "fairbanks",
        "Country": "US",
        "City ID": "7684.0",
        "Latitude": "64.84",
        "Longitude": "-147.72",
        "Temperature (F)": "64.0",
        "Humidity (%)": "58.0",
        "Cloudiness (%)": "1.0",
        "Wind Speed (mph)": "3.42"
    },
    {
        "City": "norman wells",
        "Country": "CA",
        "City ID": "951.0",
        "Latitude": "65.28",
        "Longitude": "-126.83",
        "Temperature (F)": "66.2",
        "Humidity (%)": "48.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "12.75"
    },
    {
        "City": "korkino",
        "Country": "RU",
        "City ID": "8975.0",
        "Latitude": "54.89",
        "Longitude": "61.4",
        "Temperature (F)": "46.4",
        "Humidity (%)": "87.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "8.95"
    },
    {
        "City": "aviles",
        "Country": "ES",
        "City ID": "6388.0",
        "Latitude": "43.55",
        "Longitude": "-5.92",
        "Temperature (F)": "71.01",
        "Humidity (%)": "77.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "hasaki",
        "Country": "JP",
        "City ID": "7955.0",
        "Latitude": "35.73",
        "Longitude": "140.83",
        "Temperature (F)": "68.0",
        "Humidity (%)": "94.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "5.82"
    },
    {
        "City": "mayo",
        "Country": "US",
        "City ID": "5056.0",
        "Latitude": "38.89",
        "Longitude": "-76.51",
        "Temperature (F)": "88.0",
        "Humidity (%)": "45.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "9.17"
    },
    {
        "City": "bredasdorp",
        "Country": "ZA",
        "City ID": "1966.0",
        "Latitude": "-34.53",
        "Longitude": "20.04",
        "Temperature (F)": "50.0",
        "Humidity (%)": "87.0",
        "Cloudiness (%)": "5.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "portland",
        "Country": "US",
        "City ID": "5321.0",
        "Latitude": "45.52",
        "Longitude": "-122.68",
        "Temperature (F)": "78.01",
        "Humidity (%)": "46.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "5.82"
    },
    {
        "City": "husavik",
        "Country": "IS",
        "City ID": "83.0",
        "Latitude": "66.04",
        "Longitude": "-17.34",
        "Temperature (F)": "50.0",
        "Humidity (%)": "81.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "14.99"
    },
    {
        "City": "berlevag",
        "Country": "NO",
        "City ID": "1620.0",
        "Latitude": "70.86",
        "Longitude": "29.09",
        "Temperature (F)": "44.6",
        "Humidity (%)": "87.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "35.57"
    },
    {
        "City": "luderitz",
        "Country": "NA",
        "City ID": "2260.0",
        "Latitude": "-26.65",
        "Longitude": "15.16",
        "Temperature (F)": "57.2",
        "Humidity (%)": "71.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "13.87"
    },
    {
        "City": "vestmanna",
        "Country": "FO",
        "City ID": "1596.0",
        "Latitude": "62.16",
        "Longitude": "-7.17",
        "Temperature (F)": "53.6",
        "Humidity (%)": "100.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "cap malheureux",
        "Country": "MU",
        "City ID": "2002134.0",
        "Latitude": "-19.98",
        "Longitude": "57.61",
        "Temperature (F)": "73.0",
        "Humidity (%)": "76.0",
        "Cloudiness (%)": "28.0",
        "Wind Speed (mph)": "10.0"
    },
    {
        "City": "alyangula",
        "Country": "AU",
        "City ID": "9527.0",
        "Latitude": "-13.85",
        "Longitude": "136.42",
        "Temperature (F)": "73.4",
        "Humidity (%)": "88.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "2.24"
    },
    {
        "City": "grand gaube",
        "Country": "MU",
        "City ID": "2002134.0",
        "Latitude": "-20.01",
        "Longitude": "57.66",
        "Temperature (F)": "73.0",
        "Humidity (%)": "76.0",
        "Cloudiness (%)": "33.0",
        "Wind Speed (mph)": "10.0"
    },
    {
        "City": "dunedin",
        "Country": "NZ",
        "City ID": "2031989.0",
        "Latitude": "-45.87",
        "Longitude": "170.5",
        "Temperature (F)": "48.0",
        "Humidity (%)": "85.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "1.99"
    },
    {
        "City": "domat",
        "Country": "CH",
        "City ID": "2012858.0",
        "Latitude": "46.83",
        "Longitude": "9.45",
        "Temperature (F)": "66.99",
        "Humidity (%)": "68.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "3.0"
    },
    {
        "City": "puerto ayora",
        "Country": "EC",
        "City ID": "8521.0",
        "Latitude": "-0.74",
        "Longitude": "-90.35",
        "Temperature (F)": "80.6",
        "Humidity (%)": "61.0",
        "Cloudiness (%)": "55.0",
        "Wind Speed (mph)": "21.92"
    },
    {
        "City": "high level",
        "Country": "CA",
        "City ID": "867.0",
        "Latitude": "58.52",
        "Longitude": "-117.14",
        "Temperature (F)": "64.4",
        "Humidity (%)": "55.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "2.24"
    },
    {
        "City": "cape town",
        "Country": "ZA",
        "City ID": "1899.0",
        "Latitude": "-33.93",
        "Longitude": "18.42",
        "Temperature (F)": "59.0",
        "Humidity (%)": "71.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "thompson",
        "Country": "CA",
        "City ID": "935.0",
        "Latitude": "55.74",
        "Longitude": "-97.86",
        "Temperature (F)": "75.2",
        "Humidity (%)": "47.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "margate",
        "Country": "GB",
        "City ID": "1419.0",
        "Latitude": "51.38",
        "Longitude": "1.39",
        "Temperature (F)": "77.0",
        "Humidity (%)": "50.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "16.11"
    },
    {
        "City": "kodiak",
        "Country": "US",
        "City ID": "7668.0",
        "Latitude": "57.79",
        "Longitude": "-152.41",
        "Temperature (F)": "57.2",
        "Humidity (%)": "58.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "9.17"
    },
    {
        "City": "esperance",
        "Country": "AU",
        "City ID": "9525.0",
        "Latitude": "-33.87",
        "Longitude": "121.9",
        "Temperature (F)": "55.4",
        "Humidity (%)": "54.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "mahebourg",
        "Country": "MU",
        "City ID": "2061.0",
        "Latitude": "-20.41",
        "Longitude": "57.7",
        "Temperature (F)": "71.6",
        "Humidity (%)": "83.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "17.22"
    },
    {
        "City": "torbay",
        "Country": "CA",
        "City ID": "998.0",
        "Latitude": "47.67",
        "Longitude": "-52.73",
        "Temperature (F)": "75.99",
        "Humidity (%)": "64.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "18.34"
    },
    {
        "City": "bodden town",
        "Country": "KY",
        "City ID": "7265.0",
        "Latitude": "19.28",
        "Longitude": "-81.25",
        "Temperature (F)": "87.8",
        "Humidity (%)": "79.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "11.41"
    },
    {
        "City": "cascais",
        "Country": "PT",
        "City ID": "6873.0",
        "Latitude": "38.7",
        "Longitude": "-9.42",
        "Temperature (F)": "70.0",
        "Humidity (%)": "72.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "11.41"
    },
    {
        "City": "yeppoon",
        "Country": "AU",
        "City ID": "9499.0",
        "Latitude": "-23.13",
        "Longitude": "150.73",
        "Temperature (F)": "46.4",
        "Humidity (%)": "81.0",
        "Cloudiness (%)": "7.0",
        "Wind Speed (mph)": "6.82"
    },
    {
        "City": "aswan",
        "Country": "EG",
        "City ID": "2526.0",
        "Latitude": "24.09",
        "Longitude": "32.91",
        "Temperature (F)": "96.8",
        "Humidity (%)": "15.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "17.22"
    },
    {
        "City": "khani",
        "Country": "GE",
        "City ID": "8856.0",
        "Latitude": "41.96",
        "Longitude": "42.96",
        "Temperature (F)": "75.2",
        "Humidity (%)": "78.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "5.82"
    },
    {
        "City": "uppsala",
        "Country": "SE",
        "City ID": "1731.0",
        "Latitude": "60.0",
        "Longitude": "17.75",
        "Temperature (F)": "80.6",
        "Humidity (%)": "42.0",
        "Cloudiness (%)": "66.0",
        "Wind Speed (mph)": "12.75"
    },
    {
        "City": "flinders",
        "Country": "AU",
        "City ID": "2033627.0",
        "Latitude": "-34.58",
        "Longitude": "150.86",
        "Temperature (F)": "53.01",
        "Humidity (%)": "77.0",
        "Cloudiness (%)": "46.0",
        "Wind Speed (mph)": "3.0"
    },
    {
        "City": "nago",
        "Country": "JP",
        "City ID": "8138.0",
        "Latitude": "26.59",
        "Longitude": "127.98",
        "Temperature (F)": "73.4",
        "Humidity (%)": "94.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "8.08"
    },
    {
        "City": "praia",
        "Country": "CV",
        "City ID": "2462.0",
        "Latitude": "14.92",
        "Longitude": "-23.51",
        "Temperature (F)": "80.6",
        "Humidity (%)": "61.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "19.46"
    },
    {
        "City": "banjar",
        "Country": "ID",
        "City ID": "9333.0",
        "Latitude": "-8.19",
        "Longitude": "114.97",
        "Temperature (F)": "77.0",
        "Humidity (%)": "100.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "1.12"
    },
    {
        "City": "salta",
        "Country": "AR",
        "City ID": "8267.0",
        "Latitude": "-24.79",
        "Longitude": "-65.41",
        "Temperature (F)": "53.6",
        "Humidity (%)": "54.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "3.36"
    },
    {
        "City": "huescar",
        "Country": "ES",
        "City ID": "2004386.0",
        "Latitude": "37.81",
        "Longitude": "-2.54",
        "Temperature (F)": "81.0",
        "Humidity (%)": "34.0",
        "Cloudiness (%)": "16.0",
        "Wind Speed (mph)": "12.08"
    },
    {
        "City": "lumberton",
        "Country": "US",
        "City ID": "4863.0",
        "Latitude": "34.62",
        "Longitude": "-79.01",
        "Temperature (F)": "87.8",
        "Humidity (%)": "38.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "floirac",
        "Country": "FR",
        "City ID": "6450.0",
        "Latitude": "44.83",
        "Longitude": "-0.51",
        "Temperature (F)": "77.0",
        "Humidity (%)": "64.0",
        "Cloudiness (%)": "83.0",
        "Wind Speed (mph)": "11.41"
    },
    {
        "City": "casablanca",
        "Country": "MA",
        "City ID": "2386.0",
        "Latitude": "33.59",
        "Longitude": "-7.62",
        "Temperature (F)": "71.6",
        "Humidity (%)": "64.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "18.34"
    },
    {
        "City": "cochrane",
        "Country": "CA",
        "City ID": "763.0",
        "Latitude": "51.18",
        "Longitude": "-114.47",
        "Temperature (F)": "75.2",
        "Humidity (%)": "29.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "5.82"
    },
    {
        "City": "sroda wielkopolska",
        "Country": "PL",
        "City ID": "1710.0",
        "Latitude": "52.23",
        "Longitude": "17.28",
        "Temperature (F)": "66.2",
        "Humidity (%)": "88.0",
        "Cloudiness (%)": "37.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "haverfordwest",
        "Country": "GB",
        "City ID": "1434.0",
        "Latitude": "51.8",
        "Longitude": "-4.97",
        "Temperature (F)": "63.0",
        "Humidity (%)": "77.0",
        "Cloudiness (%)": "82.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "pacific grove",
        "Country": "US",
        "City ID": "4980.0",
        "Latitude": "36.62",
        "Longitude": "-121.92",
        "Temperature (F)": "72.0",
        "Humidity (%)": "72.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "camacha",
        "Country": "PT",
        "City ID": "6902.0",
        "Latitude": "33.08",
        "Longitude": "-16.33",
        "Temperature (F)": "71.6",
        "Humidity (%)": "64.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "san patricio",
        "Country": "MX",
        "City ID": "7166.0",
        "Latitude": "19.22",
        "Longitude": "-104.7",
        "Temperature (F)": "80.6",
        "Humidity (%)": "83.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "ribeira grande",
        "Country": "PT",
        "City ID": "6883.0",
        "Latitude": "38.52",
        "Longitude": "-28.7",
        "Temperature (F)": "71.6",
        "Humidity (%)": "78.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "17.22"
    },
    {
        "City": "warrington",
        "Country": "GB",
        "City ID": "1399.0",
        "Latitude": "53.39",
        "Longitude": "-2.58",
        "Temperature (F)": "68.0",
        "Humidity (%)": "72.0",
        "Cloudiness (%)": "47.0",
        "Wind Speed (mph)": "8.05"
    },
    {
        "City": "vardo",
        "Country": "NO",
        "City ID": "1666.0",
        "Latitude": "70.37",
        "Longitude": "31.11",
        "Temperature (F)": "48.2",
        "Humidity (%)": "70.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "23.04"
    },
    {
        "City": "lebanon",
        "Country": "US",
        "City ID": "4821.0",
        "Latitude": "36.21",
        "Longitude": "-86.29",
        "Temperature (F)": "86.0",
        "Humidity (%)": "54.0",
        "Cloudiness (%)": "1.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "san nicolas",
        "Country": "PH",
        "City ID": "8159.0",
        "Latitude": "18.17",
        "Longitude": "120.6",
        "Temperature (F)": "78.8",
        "Humidity (%)": "94.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "2.95"
    },
    {
        "City": "springfield",
        "Country": "US",
        "City ID": "5821.0",
        "Latitude": "37.22",
        "Longitude": "-93.3",
        "Temperature (F)": "86.0",
        "Humidity (%)": "66.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "12.75"
    },
    {
        "City": "pisco",
        "Country": "PE",
        "City ID": "8691.0",
        "Latitude": "-13.7",
        "Longitude": "-76.22",
        "Temperature (F)": "66.0",
        "Humidity (%)": "77.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "8.05"
    },
    {
        "City": "nantucket",
        "Country": "US",
        "City ID": "3218.0",
        "Latitude": "41.28",
        "Longitude": "-70.1",
        "Temperature (F)": "71.6",
        "Humidity (%)": "73.0",
        "Cloudiness (%)": "1.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "rundu",
        "Country": "NA",
        "City ID": "2277.0",
        "Latitude": "-17.93",
        "Longitude": "19.77",
        "Temperature (F)": "64.4",
        "Humidity (%)": "34.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "lake city",
        "Country": "US",
        "City ID": "4685.0",
        "Latitude": "30.19",
        "Longitude": "-82.64",
        "Temperature (F)": "93.99",
        "Humidity (%)": "52.0",
        "Cloudiness (%)": "1.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "arvika",
        "Country": "SE",
        "City ID": "1779.0",
        "Latitude": "59.66",
        "Longitude": "12.59",
        "Temperature (F)": "82.99",
        "Humidity (%)": "34.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "5.82"
    },
    {
        "City": "langham",
        "Country": "CA",
        "City ID": "977.0",
        "Latitude": "52.37",
        "Longitude": "-106.97",
        "Temperature (F)": "80.6",
        "Humidity (%)": "36.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "8.05"
    },
    {
        "City": "ulladulla",
        "Country": "AU",
        "City ID": "9594.0",
        "Latitude": "-35.35",
        "Longitude": "150.47",
        "Temperature (F)": "48.99",
        "Humidity (%)": "93.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "rustam",
        "Country": "PK",
        "City ID": "7591.0",
        "Latitude": "27.97",
        "Longitude": "68.8",
        "Temperature (F)": "98.6",
        "Humidity (%)": "47.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "9.17"
    },
    {
        "City": "machacamarca",
        "Country": "BO",
        "City ID": "8625.0",
        "Latitude": "-18.17",
        "Longitude": "-67.03",
        "Temperature (F)": "59.0",
        "Humidity (%)": "30.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "16.11"
    },
    {
        "City": "wajir",
        "Country": "KE",
        "City ID": "2571.0",
        "Latitude": "1.75",
        "Longitude": "40.06",
        "Temperature (F)": "86.0",
        "Humidity (%)": "48.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "la ronge",
        "Country": "CA",
        "City ID": "949.0",
        "Latitude": "55.1",
        "Longitude": "-105.28",
        "Temperature (F)": "69.8",
        "Humidity (%)": "46.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "11.41"
    },
    {
        "City": "dauphin",
        "Country": "CA",
        "City ID": "780.0",
        "Latitude": "51.15",
        "Longitude": "-100.05",
        "Temperature (F)": "80.6",
        "Humidity (%)": "42.0",
        "Cloudiness (%)": "1.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "novopokrovka",
        "Country": "UA",
        "City ID": "8905.0",
        "Latitude": "49.84",
        "Longitude": "36.55",
        "Temperature (F)": "73.4",
        "Humidity (%)": "60.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "8.95"
    },
    {
        "City": "asyut",
        "Country": "EG",
        "City ID": "2510.0",
        "Latitude": "27.18",
        "Longitude": "31.18",
        "Temperature (F)": "89.6",
        "Humidity (%)": "27.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "13.87"
    },
    {
        "City": "vila velha",
        "Country": "BR",
        "City ID": "8474.0",
        "Latitude": "-20.33",
        "Longitude": "-40.29",
        "Temperature (F)": "84.99",
        "Humidity (%)": "45.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "sibu",
        "Country": "MY",
        "City ID": "9369.0",
        "Latitude": "2.3",
        "Longitude": "111.82",
        "Temperature (F)": "75.2",
        "Humidity (%)": "94.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "saint-gaudens",
        "Country": "FR",
        "City ID": "6471.0",
        "Latitude": "43.08",
        "Longitude": "0.67",
        "Temperature (F)": "78.01",
        "Humidity (%)": "78.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "sioux lookout",
        "Country": "CA",
        "City ID": "979.0",
        "Latitude": "50.1",
        "Longitude": "-91.92",
        "Temperature (F)": "71.6",
        "Humidity (%)": "78.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "13.87"
    },
    {
        "City": "kemptville",
        "Country": "CA",
        "City ID": "5184.0",
        "Latitude": "45.02",
        "Longitude": "-75.64",
        "Temperature (F)": "80.6",
        "Humidity (%)": "44.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "kashi",
        "Country": "CN",
        "City ID": "9676.0",
        "Latitude": "39.45",
        "Longitude": "75.98",
        "Temperature (F)": "75.2",
        "Humidity (%)": "25.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "6.71"
    },
    {
        "City": "saint-joseph",
        "Country": "RE",
        "City ID": "2127.0",
        "Latitude": "-21.37",
        "Longitude": "55.62",
        "Temperature (F)": "71.6",
        "Humidity (%)": "73.0",
        "Cloudiness (%)": "47.0",
        "Wind Speed (mph)": "20.8"
    },
    {
        "City": "avera",
        "Country": "US",
        "City ID": "2827.0",
        "Latitude": "33.19",
        "Longitude": "-82.53",
        "Temperature (F)": "89.6",
        "Humidity (%)": "49.0",
        "Cloudiness (%)": "1.0",
        "Wind Speed (mph)": "9.17"
    },
    {
        "City": "komsomolskiy",
        "Country": "UZ",
        "City ID": "9011.0",
        "Latitude": "40.43",
        "Longitude": "71.72",
        "Temperature (F)": "77.0",
        "Humidity (%)": "36.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "niles",
        "Country": "US",
        "City ID": "5228.0",
        "Latitude": "42.02",
        "Longitude": "-87.8",
        "Temperature (F)": "72.0",
        "Humidity (%)": "88.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "las cruces",
        "Country": "US",
        "City ID": "4757.0",
        "Latitude": "32.31",
        "Longitude": "-106.78",
        "Temperature (F)": "97.0",
        "Humidity (%)": "11.0",
        "Cloudiness (%)": "1.0",
        "Wind Speed (mph)": "3.36"
    },
    {
        "City": "katsuura",
        "Country": "JP",
        "City ID": "8052.0",
        "Latitude": "35.13",
        "Longitude": "140.3",
        "Temperature (F)": "75.2",
        "Humidity (%)": "94.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "5.82"
    },
    {
        "City": "carnarvon",
        "Country": "AU",
        "City ID": "9505.0",
        "Latitude": "-24.87",
        "Longitude": "113.63",
        "Temperature (F)": "57.2",
        "Humidity (%)": "93.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "lasa",
        "Country": "IT",
        "City ID": "6813.0",
        "Latitude": "46.62",
        "Longitude": "10.7",
        "Temperature (F)": "63.0",
        "Humidity (%)": "87.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "hamilton",
        "Country": "US",
        "City ID": "4776.0",
        "Latitude": "39.18",
        "Longitude": "-84.53",
        "Temperature (F)": "84.99",
        "Humidity (%)": "54.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "12.75"
    },
    {
        "City": "boat of garten",
        "Country": "GB",
        "City ID": "1435.0",
        "Latitude": "57.25",
        "Longitude": "-3.76",
        "Temperature (F)": "66.2",
        "Humidity (%)": "93.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "2.24"
    },
    {
        "City": "bulnes",
        "Country": "CL",
        "City ID": "8483.0",
        "Latitude": "-36.74",
        "Longitude": "-72.3",
        "Temperature (F)": "46.4",
        "Humidity (%)": "87.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "19.46"
    },
    {
        "City": "bronnoysund",
        "Country": "NO",
        "City ID": "1611.0",
        "Latitude": "65.46",
        "Longitude": "12.2",
        "Temperature (F)": "60.8",
        "Humidity (%)": "77.0",
        "Cloudiness (%)": "78.0",
        "Wind Speed (mph)": "12.75"
    },
    {
        "City": "naze",
        "Country": "JP",
        "City ID": "8002.0",
        "Latitude": "28.37",
        "Longitude": "129.48",
        "Temperature (F)": "78.8",
        "Humidity (%)": "100.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "8.05"
    },
    {
        "City": "longyearbyen",
        "Country": "SJ",
        "City ID": "1663.0",
        "Latitude": "78.22",
        "Longitude": "15.64",
        "Temperature (F)": "50.0",
        "Humidity (%)": "71.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "12.75"
    },
    {
        "City": "gouyave",
        "Country": "GD",
        "City ID": "8781.0",
        "Latitude": "12.16",
        "Longitude": "-61.73",
        "Temperature (F)": "87.8",
        "Humidity (%)": "70.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "17.22"
    },
    {
        "City": "belmonte",
        "Country": "BR",
        "City ID": "8422.0",
        "Latitude": "-15.86",
        "Longitude": "-38.88",
        "Temperature (F)": "77.0",
        "Humidity (%)": "73.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "sterling",
        "Country": "US",
        "City ID": "4481.0",
        "Latitude": "39.01",
        "Longitude": "-77.43",
        "Temperature (F)": "87.01",
        "Humidity (%)": "39.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "13.87"
    },
    {
        "City": "ikryanoye",
        "Country": "RU",
        "City ID": "8974.0",
        "Latitude": "46.09",
        "Longitude": "47.73",
        "Temperature (F)": "69.8",
        "Humidity (%)": "32.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "6.71"
    },
    {
        "City": "buchanan",
        "Country": "LR",
        "City ID": "2389.0",
        "Latitude": "5.88",
        "Longitude": "-10.05",
        "Temperature (F)": "78.8",
        "Humidity (%)": "94.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "10.09"
    },
    {
        "City": "ketchikan",
        "Country": "US",
        "City ID": "7741.0",
        "Latitude": "55.34",
        "Longitude": "-131.65",
        "Temperature (F)": "53.6",
        "Humidity (%)": "93.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "9.17"
    },
    {
        "City": "phanom sarakham",
        "Country": "TH",
        "City ID": "2000906.0",
        "Latitude": "13.75",
        "Longitude": "101.36",
        "Temperature (F)": "90.0",
        "Humidity (%)": "76.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "4.79"
    },
    {
        "City": "nybro",
        "Country": "SE",
        "City ID": "1757.0",
        "Latitude": "56.74",
        "Longitude": "15.91",
        "Temperature (F)": "75.2",
        "Humidity (%)": "53.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "8.05"
    },
    {
        "City": "portobelo",
        "Country": "PA",
        "City ID": "2013151.0",
        "Latitude": "9.55",
        "Longitude": "-79.65",
        "Temperature (F)": "84.99",
        "Humidity (%)": "83.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "5.01"
    },
    {
        "City": "bereda",
        "Country": "ES",
        "City ID": "2013071.0",
        "Latitude": "43.27",
        "Longitude": "-7.54",
        "Temperature (F)": "66.99",
        "Humidity (%)": "79.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "11.01"
    },
    {
        "City": "port macquarie",
        "Country": "AU",
        "City ID": "2000886.0",
        "Latitude": "-31.43",
        "Longitude": "152.92",
        "Temperature (F)": "51.01",
        "Humidity (%)": "89.0",
        "Cloudiness (%)": "93.0",
        "Wind Speed (mph)": "8.55"
    },
    {
        "City": "northam",
        "Country": "GB",
        "City ID": "2005965.0",
        "Latitude": "51.03",
        "Longitude": "-4.22",
        "Temperature (F)": "64.99",
        "Humidity (%)": "73.0",
        "Cloudiness (%)": "89.0",
        "Wind Speed (mph)": "8.01"
    },
    {
        "City": "ankara",
        "Country": "TR",
        "City ID": "6948.0",
        "Latitude": "39.92",
        "Longitude": "32.85",
        "Temperature (F)": "73.4",
        "Humidity (%)": "49.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "gillette",
        "Country": "US",
        "City ID": "2006559.0",
        "Latitude": "44.29",
        "Longitude": "-105.5",
        "Temperature (F)": "77.0",
        "Humidity (%)": "44.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "3.0"
    },
    {
        "City": "belle glade",
        "Country": "US",
        "City ID": "2007993.0",
        "Latitude": "26.68",
        "Longitude": "-80.67",
        "Temperature (F)": "91.99",
        "Humidity (%)": "62.0",
        "Cloudiness (%)": "97.0",
        "Wind Speed (mph)": "3.0"
    },
    {
        "City": "plouzane",
        "Country": "FR",
        "City ID": "6554.0",
        "Latitude": "48.38",
        "Longitude": "-4.62",
        "Temperature (F)": "64.4",
        "Humidity (%)": "77.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "20.8"
    },
    {
        "City": "broome",
        "Country": "US",
        "City ID": "3429.0",
        "Latitude": "42.25",
        "Longitude": "-75.83",
        "Temperature (F)": "80.01",
        "Humidity (%)": "41.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "9.17"
    },
    {
        "City": "marawi",
        "Country": "PH",
        "City ID": "2007154.0",
        "Latitude": "8.0",
        "Longitude": "124.29",
        "Temperature (F)": "75.0",
        "Humidity (%)": "94.0",
        "Cloudiness (%)": "77.0",
        "Wind Speed (mph)": "4.0"
    },
    {
        "City": "neka",
        "Country": "IR",
        "City ID": "7498.0",
        "Latitude": "36.65",
        "Longitude": "53.3",
        "Temperature (F)": "77.0",
        "Humidity (%)": "78.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "puerto ayacucho",
        "Country": "VE",
        "City ID": "8586.0",
        "Latitude": "5.66",
        "Longitude": "-67.62",
        "Temperature (F)": "89.6",
        "Humidity (%)": "55.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "ordubad",
        "Country": "AZ",
        "City ID": "8839.0",
        "Latitude": "38.91",
        "Longitude": "46.02",
        "Temperature (F)": "78.8",
        "Humidity (%)": "31.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "13.87"
    },
    {
        "City": "greencastle",
        "Country": "US",
        "City ID": "4256.0",
        "Latitude": "39.64",
        "Longitude": "-86.86",
        "Temperature (F)": "89.01",
        "Humidity (%)": "58.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "red bluff",
        "Country": "US",
        "City ID": "5626.0",
        "Latitude": "40.18",
        "Longitude": "-122.24",
        "Temperature (F)": "100.4",
        "Humidity (%)": "17.0",
        "Cloudiness (%)": "1.0",
        "Wind Speed (mph)": "12.75"
    },
    {
        "City": "los llanos de aridane",
        "Country": "ES",
        "City ID": "2377.0",
        "Latitude": "28.66",
        "Longitude": "-17.92",
        "Temperature (F)": "73.4",
        "Humidity (%)": "69.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "18.34"
    },
    {
        "City": "cuiaba",
        "Country": "BR",
        "City ID": "8352.0",
        "Latitude": "-15.6",
        "Longitude": "-56.1",
        "Temperature (F)": "86.0",
        "Humidity (%)": "48.0",
        "Cloudiness (%)": "11.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "vestmannaeyjar",
        "Country": "IS",
        "City ID": "93.0",
        "Latitude": "63.44",
        "Longitude": "-20.27",
        "Temperature (F)": "53.6",
        "Humidity (%)": "71.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "prince albert",
        "Country": "CA",
        "City ID": "875.0",
        "Latitude": "53.2",
        "Longitude": "-105.77",
        "Temperature (F)": "66.2",
        "Humidity (%)": "59.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "5.82"
    },
    {
        "City": "tabatinga",
        "Country": "BR",
        "City ID": "8444.0",
        "Latitude": "-4.25",
        "Longitude": "-69.94",
        "Temperature (F)": "87.8",
        "Humidity (%)": "66.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "5.82"
    },
    {
        "City": "lowestoft",
        "Country": "GB",
        "City ID": "2019850.0",
        "Latitude": "52.48",
        "Longitude": "1.75",
        "Temperature (F)": "75.99",
        "Humidity (%)": "85.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "8.01"
    },
    {
        "City": "kaitangata",
        "Country": "NZ",
        "City ID": "2031989.0",
        "Latitude": "-46.28",
        "Longitude": "169.85",
        "Temperature (F)": "46.99",
        "Humidity (%)": "85.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "1.99"
    },
    {
        "City": "touros",
        "Country": "BR",
        "City ID": "8452.0",
        "Latitude": "-5.2",
        "Longitude": "-35.46",
        "Temperature (F)": "82.4",
        "Humidity (%)": "69.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "14.99"
    },
    {
        "City": "rovaniemi",
        "Country": "FI",
        "City ID": "1354.0",
        "Latitude": "66.5",
        "Longitude": "25.72",
        "Temperature (F)": "64.4",
        "Humidity (%)": "39.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "san luis de planes",
        "Country": "HN",
        "City ID": "7097.0",
        "Latitude": "14.98",
        "Longitude": "-88.13",
        "Temperature (F)": "93.2",
        "Humidity (%)": "46.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "11.41"
    },
    {
        "City": "nuuk",
        "Country": "GL",
        "City ID": "86.0",
        "Latitude": "64.18",
        "Longitude": "-51.72",
        "Temperature (F)": "46.4",
        "Humidity (%)": "65.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "8.05"
    },
    {
        "City": "kiama",
        "Country": "AU",
        "City ID": "20106.0",
        "Latitude": "-34.68",
        "Longitude": "150.87",
        "Temperature (F)": "53.01",
        "Humidity (%)": "79.0",
        "Cloudiness (%)": "67.0",
        "Wind Speed (mph)": "1.99"
    },
    {
        "City": "port moresby",
        "Country": "PG",
        "City ID": "42.0",
        "Latitude": "-9.44",
        "Longitude": "147.18",
        "Temperature (F)": "77.0",
        "Humidity (%)": "88.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "11.41"
    },
    {
        "City": "le port",
        "Country": "RE",
        "City ID": "2133.0",
        "Latitude": "-20.94",
        "Longitude": "55.29",
        "Temperature (F)": "71.6",
        "Humidity (%)": "82.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "21.92"
    },
    {
        "City": "brawley",
        "Country": "US",
        "City ID": "4540.0",
        "Latitude": "32.98",
        "Longitude": "-115.53",
        "Temperature (F)": "99.0",
        "Humidity (%)": "17.0",
        "Cloudiness (%)": "1.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "cotacachi",
        "Country": "EC",
        "City ID": "8555.0",
        "Latitude": "0.3",
        "Longitude": "-78.27",
        "Temperature (F)": "66.2",
        "Humidity (%)": "59.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "12.75"
    },
    {
        "City": "saint-leu",
        "Country": "RE",
        "City ID": "2127.0",
        "Latitude": "-21.15",
        "Longitude": "55.28",
        "Temperature (F)": "71.6",
        "Humidity (%)": "73.0",
        "Cloudiness (%)": "33.0",
        "Wind Speed (mph)": "20.8"
    },
    {
        "City": "smithers",
        "Country": "CA",
        "City ID": "990.0",
        "Latitude": "54.78",
        "Longitude": "-127.17",
        "Temperature (F)": "55.4",
        "Humidity (%)": "66.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "2.24"
    },
    {
        "City": "fairmont",
        "Country": "US",
        "City ID": "2006787.0",
        "Latitude": "39.49",
        "Longitude": "-80.14",
        "Temperature (F)": "86.0",
        "Humidity (%)": "48.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "9.86"
    },
    {
        "City": "marmora",
        "Country": "IT",
        "City ID": "6754.0",
        "Latitude": "44.46",
        "Longitude": "7.09",
        "Temperature (F)": "78.01",
        "Humidity (%)": "64.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "corinto",
        "Country": "GR",
        "City ID": "2002027.0",
        "Latitude": "37.94",
        "Longitude": "22.96",
        "Temperature (F)": "82.99",
        "Humidity (%)": "49.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "3.0"
    },
    {
        "City": "keita",
        "Country": "NE",
        "City ID": "1189.0",
        "Latitude": "14.76",
        "Longitude": "5.77",
        "Temperature (F)": "93.2",
        "Humidity (%)": "30.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "campbell river",
        "Country": "CA",
        "City ID": "752.0",
        "Latitude": "50.02",
        "Longitude": "-125.24",
        "Temperature (F)": "66.2",
        "Humidity (%)": "68.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "2.84"
    },
    {
        "City": "ilulissat",
        "Country": "GL",
        "City ID": "165.0",
        "Latitude": "69.22",
        "Longitude": "-51.1",
        "Temperature (F)": "39.2",
        "Humidity (%)": "86.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "luoyang",
        "Country": "CN",
        "City ID": "266522.0",
        "Latitude": "34.68",
        "Longitude": "112.45",
        "Temperature (F)": "80.01",
        "Humidity (%)": "99.0",
        "Cloudiness (%)": "76.0",
        "Wind Speed (mph)": "5.3"
    },
    {
        "City": "mount gambier",
        "Country": "AU",
        "City ID": "9560.0",
        "Latitude": "-37.83",
        "Longitude": "140.77",
        "Temperature (F)": "44.6",
        "Humidity (%)": "87.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "8.05"
    },
    {
        "City": "mount isa",
        "Country": "AU",
        "City ID": "9495.0",
        "Latitude": "-20.73",
        "Longitude": "139.5",
        "Temperature (F)": "50.0",
        "Humidity (%)": "39.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "5.82"
    },
    {
        "City": "saint george",
        "Country": "US",
        "City ID": "5832.0",
        "Latitude": "37.1",
        "Longitude": "-113.58",
        "Temperature (F)": "93.99",
        "Humidity (%)": "17.0",
        "Cloudiness (%)": "1.0",
        "Wind Speed (mph)": "3.04"
    },
    {
        "City": "khorramshahr",
        "Country": "IR",
        "City ID": "7439.0",
        "Latitude": "30.44",
        "Longitude": "48.17",
        "Temperature (F)": "96.8",
        "Humidity (%)": "18.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "santiago",
        "Country": "CL",
        "City ID": "8506.0",
        "Latitude": "-33.46",
        "Longitude": "-70.65",
        "Temperature (F)": "57.2",
        "Humidity (%)": "33.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "3.36"
    },
    {
        "City": "souillac",
        "Country": "MU",
        "City ID": "2061.0",
        "Latitude": "-20.52",
        "Longitude": "57.52",
        "Temperature (F)": "71.6",
        "Humidity (%)": "83.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "17.22"
    },
    {
        "City": "shelbyville",
        "Country": "US",
        "City ID": "5960.0",
        "Latitude": "35.48",
        "Longitude": "-86.46",
        "Temperature (F)": "80.01",
        "Humidity (%)": "74.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "lloydminster",
        "Country": "CA",
        "City ID": "850.0",
        "Latitude": "53.28",
        "Longitude": "-110.0",
        "Temperature (F)": "66.2",
        "Humidity (%)": "55.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "lahaina",
        "Country": "US",
        "City ID": "7851.0",
        "Latitude": "20.88",
        "Longitude": "-156.68",
        "Temperature (F)": "82.4",
        "Humidity (%)": "65.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "11.41"
    },
    {
        "City": "narsaq",
        "Country": "GL",
        "City ID": "47.0",
        "Latitude": "60.92",
        "Longitude": "-46.05",
        "Temperature (F)": "55.4",
        "Humidity (%)": "50.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "bathsheba",
        "Country": "BB",
        "City ID": "8772.0",
        "Latitude": "13.22",
        "Longitude": "-59.52",
        "Temperature (F)": "86.0",
        "Humidity (%)": "74.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "23.04"
    },
    {
        "City": "ilheus",
        "Country": "BR",
        "City ID": "8386.0",
        "Latitude": "-14.79",
        "Longitude": "-39.05",
        "Temperature (F)": "82.4",
        "Humidity (%)": "74.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "isla mujeres",
        "Country": "MX",
        "City ID": "7177.0",
        "Latitude": "21.23",
        "Longitude": "-86.73",
        "Temperature (F)": "87.8",
        "Humidity (%)": "74.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "swellendam",
        "Country": "ZA",
        "City ID": "1966.0",
        "Latitude": "-34.02",
        "Longitude": "20.44",
        "Temperature (F)": "50.0",
        "Humidity (%)": "87.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "yarmouth",
        "Country": "US",
        "City ID": "4454.0",
        "Latitude": "41.71",
        "Longitude": "-70.23",
        "Temperature (F)": "78.8",
        "Humidity (%)": "65.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "morwell",
        "Country": "AU",
        "City ID": "2021657.0",
        "Latitude": "-38.23",
        "Longitude": "146.4",
        "Temperature (F)": "35.01",
        "Humidity (%)": "96.0",
        "Cloudiness (%)": "3.0",
        "Wind Speed (mph)": "0.76"
    },
    {
        "City": "broken hill",
        "Country": "AU",
        "City ID": "9491.0",
        "Latitude": "-31.95",
        "Longitude": "141.43",
        "Temperature (F)": "44.6",
        "Humidity (%)": "65.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "ocean city",
        "Country": "US",
        "City ID": "3222.0",
        "Latitude": "39.28",
        "Longitude": "-74.57",
        "Temperature (F)": "89.6",
        "Humidity (%)": "31.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "11.41"
    },
    {
        "City": "belgrade",
        "Country": "RS",
        "City ID": "7028.0",
        "Latitude": "44.8",
        "Longitude": "20.47",
        "Temperature (F)": "80.6",
        "Humidity (%)": "57.0",
        "Cloudiness (%)": "98.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "lyngseidet",
        "Country": "NO",
        "City ID": "1672.0",
        "Latitude": "69.58",
        "Longitude": "20.22",
        "Temperature (F)": "51.8",
        "Humidity (%)": "71.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "25.28"
    },
    {
        "City": "takaka",
        "Country": "NZ",
        "City ID": "2002166.0",
        "Latitude": "-40.85",
        "Longitude": "172.8",
        "Temperature (F)": "55.0",
        "Humidity (%)": "80.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "7.0"
    },
    {
        "City": "cabra",
        "Country": "ES",
        "City ID": "2008401.0",
        "Latitude": "37.47",
        "Longitude": "-4.44",
        "Temperature (F)": "84.0",
        "Humidity (%)": "29.0",
        "Cloudiness (%)": "94.0",
        "Wind Speed (mph)": "5.01"
    },
    {
        "City": "honiara",
        "Country": "SB",
        "City ID": "2.0",
        "Latitude": "-9.43",
        "Longitude": "159.95",
        "Temperature (F)": "71.6",
        "Humidity (%)": "94.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "2.24"
    },
    {
        "City": "atherton",
        "Country": "GB",
        "City ID": "2001932.0",
        "Latitude": "53.52",
        "Longitude": "-2.49",
        "Temperature (F)": "66.99",
        "Humidity (%)": "73.0",
        "Cloudiness (%)": "73.0",
        "Wind Speed (mph)": "8.01"
    },
    {
        "City": "vammala",
        "Country": "FI",
        "City ID": "1360.0",
        "Latitude": "61.33",
        "Longitude": "22.9",
        "Temperature (F)": "79.0",
        "Humidity (%)": "34.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "12.75"
    },
    {
        "City": "hervey bay",
        "Country": "AU",
        "City ID": "9501.0",
        "Latitude": "-25.3",
        "Longitude": "152.85",
        "Temperature (F)": "55.99",
        "Humidity (%)": "82.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "twin falls",
        "Country": "US",
        "City ID": "6085.0",
        "Latitude": "42.56",
        "Longitude": "-114.46",
        "Temperature (F)": "78.8",
        "Humidity (%)": "34.0",
        "Cloudiness (%)": "1.0",
        "Wind Speed (mph)": "8.05"
    },
    {
        "City": "palmer",
        "Country": "US",
        "City ID": "3598.0",
        "Latitude": "42.16",
        "Longitude": "-72.33",
        "Temperature (F)": "82.4",
        "Humidity (%)": "34.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "8.05"
    },
    {
        "City": "andenes",
        "Country": "NO",
        "City ID": "1603.0",
        "Latitude": "69.31",
        "Longitude": "16.12",
        "Temperature (F)": "50.0",
        "Humidity (%)": "87.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "kosmach",
        "Country": "UA",
        "City ID": "8906.0",
        "Latitude": "48.75",
        "Longitude": "24.37",
        "Temperature (F)": "71.6",
        "Humidity (%)": "73.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "4.47"
    },
    {
        "City": "port hedland",
        "Country": "AU",
        "City ID": "9585.0",
        "Latitude": "-20.32",
        "Longitude": "118.57",
        "Temperature (F)": "55.4",
        "Humidity (%)": "58.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "5.82"
    },
    {
        "City": "bayonet point",
        "Country": "US",
        "City ID": "19854.0",
        "Latitude": "28.33",
        "Longitude": "-82.68",
        "Temperature (F)": "97.0",
        "Humidity (%)": "48.0",
        "Cloudiness (%)": "53.0",
        "Wind Speed (mph)": "1.99"
    },
    {
        "City": "la palma",
        "Country": "US",
        "City ID": "4154.0",
        "Latitude": "33.85",
        "Longitude": "-118.05",
        "Temperature (F)": "78.01",
        "Humidity (%)": "57.0",
        "Cloudiness (%)": "1.0",
        "Wind Speed (mph)": "8.72"
    },
    {
        "City": "bundaberg",
        "Country": "AU",
        "City ID": "9501.0",
        "Latitude": "-24.85",
        "Longitude": "152.35",
        "Temperature (F)": "55.99",
        "Humidity (%)": "82.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "kigoma",
        "Country": "TZ",
        "City ID": "2609.0",
        "Latitude": "-4.88",
        "Longitude": "29.63",
        "Temperature (F)": "77.0",
        "Humidity (%)": "65.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "1.59"
    },
    {
        "City": "hvolsvollur",
        "Country": "IS",
        "City ID": "93.0",
        "Latitude": "63.75",
        "Longitude": "-20.22",
        "Temperature (F)": "53.6",
        "Humidity (%)": "71.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "changqing",
        "Country": "CN",
        "City ID": "2020829.0",
        "Latitude": "36.56",
        "Longitude": "116.73",
        "Temperature (F)": "82.0",
        "Humidity (%)": "70.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "1.03"
    },
    {
        "City": "embu",
        "Country": "BR",
        "City ID": "8446.0",
        "Latitude": "-23.65",
        "Longitude": "-46.85",
        "Temperature (F)": "63.0",
        "Humidity (%)": "87.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "12.75"
    },
    {
        "City": "norden",
        "Country": "DE",
        "City ID": "1852.0",
        "Latitude": "53.6",
        "Longitude": "7.2",
        "Temperature (F)": "84.2",
        "Humidity (%)": "30.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "orbetello",
        "Country": "IT",
        "City ID": "6793.0",
        "Latitude": "42.44",
        "Longitude": "11.22",
        "Temperature (F)": "78.8",
        "Humidity (%)": "26.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "1.16"
    },
    {
        "City": "honningsvag",
        "Country": "NO",
        "City ID": "1638.0",
        "Latitude": "70.98",
        "Longitude": "25.97",
        "Temperature (F)": "44.6",
        "Humidity (%)": "93.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "27.51"
    },
    {
        "City": "lata",
        "Country": "PT",
        "City ID": "2001739.0",
        "Latitude": "40.16",
        "Longitude": "-8.33",
        "Temperature (F)": "75.0",
        "Humidity (%)": "56.0",
        "Cloudiness (%)": "92.0",
        "Wind Speed (mph)": "5.99"
    },
    {
        "City": "general roca",
        "Country": "AR",
        "City ID": "8310.0",
        "Latitude": "-39.03",
        "Longitude": "-67.58",
        "Temperature (F)": "33.8",
        "Humidity (%)": "88.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "9.17"
    },
    {
        "City": "natchitoches",
        "Country": "US",
        "City ID": "4502.0",
        "Latitude": "31.77",
        "Longitude": "-93.13",
        "Temperature (F)": "82.4",
        "Humidity (%)": "88.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "9.15"
    },
    {
        "City": "pangnirtung",
        "Country": "CA",
        "City ID": "968.0",
        "Latitude": "66.15",
        "Longitude": "-65.71",
        "Temperature (F)": "46.4",
        "Humidity (%)": "81.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "ancud",
        "Country": "CL",
        "City ID": "8512.0",
        "Latitude": "-41.87",
        "Longitude": "-73.82",
        "Temperature (F)": "44.6",
        "Humidity (%)": "81.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "5.82"
    },
    {
        "City": "ferrol",
        "Country": "ES",
        "City ID": "6403.0",
        "Latitude": "43.48",
        "Longitude": "-8.24",
        "Temperature (F)": "68.0",
        "Humidity (%)": "77.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "16.11"
    },
    {
        "City": "calvia",
        "Country": "ES",
        "City ID": "9693.0",
        "Latitude": "39.57",
        "Longitude": "2.51",
        "Temperature (F)": "87.8",
        "Humidity (%)": "33.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "11.41"
    },
    {
        "City": "neiafu",
        "Country": "TO",
        "City ID": "7292.0",
        "Latitude": "-18.65",
        "Longitude": "-173.98",
        "Temperature (F)": "77.0",
        "Humidity (%)": "88.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "8.05"
    },
    {
        "City": "mulchen",
        "Country": "CL",
        "City ID": "8479.0",
        "Latitude": "-37.72",
        "Longitude": "-72.23",
        "Temperature (F)": "44.6",
        "Humidity (%)": "100.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "13.87"
    },
    {
        "City": "grevesmuhlen",
        "Country": "DE",
        "City ID": "2018637.0",
        "Latitude": "53.87",
        "Longitude": "11.18",
        "Temperature (F)": "79.0",
        "Humidity (%)": "73.0",
        "Cloudiness (%)": "9.0",
        "Wind Speed (mph)": "4.0"
    },
    {
        "City": "beachwood",
        "Country": "US",
        "City ID": "3602.0",
        "Latitude": "41.46",
        "Longitude": "-81.51",
        "Temperature (F)": "82.99",
        "Humidity (%)": "42.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "pangai",
        "Country": "TO",
        "City ID": "7286.0",
        "Latitude": "-19.8",
        "Longitude": "-174.35",
        "Temperature (F)": "77.0",
        "Humidity (%)": "78.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "10.29"
    },
    {
        "City": "prato",
        "Country": "IT",
        "City ID": "6804.0",
        "Latitude": "43.88",
        "Longitude": "11.09",
        "Temperature (F)": "82.99",
        "Humidity (%)": "45.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "juelsminde",
        "Country": "DK",
        "City ID": "1595.0",
        "Latitude": "55.71",
        "Longitude": "10.02",
        "Temperature (F)": "77.0",
        "Humidity (%)": "57.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "bermejo",
        "Country": "AR",
        "City ID": "8238.0",
        "Latitude": "-32.88",
        "Longitude": "-68.8",
        "Temperature (F)": "55.4",
        "Humidity (%)": "37.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "kristianstad",
        "Country": "SE",
        "City ID": "1759.0",
        "Latitude": "56.03",
        "Longitude": "14.15",
        "Temperature (F)": "72.0",
        "Humidity (%)": "68.0",
        "Cloudiness (%)": "1.0",
        "Wind Speed (mph)": "8.05"
    },
    {
        "City": "christchurch",
        "Country": "NZ",
        "City ID": "7348.0",
        "Latitude": "-43.53",
        "Longitude": "172.63",
        "Temperature (F)": "53.01",
        "Humidity (%)": "100.0",
        "Cloudiness (%)": "52.0",
        "Wind Speed (mph)": "18.34"
    },
    {
        "City": "batsfjord",
        "Country": "NO",
        "City ID": "1620.0",
        "Latitude": "70.63",
        "Longitude": "29.72",
        "Temperature (F)": "48.2",
        "Humidity (%)": "93.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "29.97"
    },
    {
        "City": "necochea",
        "Country": "AR",
        "City ID": "2019717.0",
        "Latitude": "-38.55",
        "Longitude": "-58.74",
        "Temperature (F)": "48.99",
        "Humidity (%)": "80.0",
        "Cloudiness (%)": "25.0",
        "Wind Speed (mph)": "11.01"
    },
    {
        "City": "mililani town",
        "Country": "US",
        "City ID": "7866.0",
        "Latitude": "21.45",
        "Longitude": "-158.0",
        "Temperature (F)": "82.4",
        "Humidity (%)": "65.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "5.82"
    },
    {
        "City": "yinchuan",
        "Country": "CN",
        "City ID": "2000025.0",
        "Latitude": "38.47",
        "Longitude": "106.27",
        "Temperature (F)": "73.0",
        "Humidity (%)": "31.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "3.0"
    },
    {
        "City": "burnie",
        "Country": "AU",
        "City ID": "50154.0",
        "Latitude": "-41.07",
        "Longitude": "145.92",
        "Temperature (F)": "39.0",
        "Humidity (%)": "82.0",
        "Cloudiness (%)": "78.0",
        "Wind Speed (mph)": "5.97"
    },
    {
        "City": "paraiso",
        "Country": "CR",
        "City ID": "7205.0",
        "Latitude": "9.84",
        "Longitude": "-83.87",
        "Temperature (F)": "84.2",
        "Humidity (%)": "61.0",
        "Cloudiness (%)": "75.0",
        "Wind Speed (mph)": "16.11"
    },
    {
        "City": "coquimbo",
        "Country": "CL",
        "City ID": "8514.0",
        "Latitude": "-29.95",
        "Longitude": "-71.34",
        "Temperature (F)": "59.0",
        "Humidity (%)": "72.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "12.75"
    },
    {
        "City": "shimoda",
        "Country": "JP",
        "City ID": "2019346.0",
        "Latitude": "34.67",
        "Longitude": "138.95",
        "Temperature (F)": "72.0",
        "Humidity (%)": "90.0",
        "Cloudiness (%)": "97.0",
        "Wind Speed (mph)": "1.99"
    },
    {
        "City": "huron",
        "Country": "US",
        "City ID": "2001593.0",
        "Latitude": "41.15",
        "Longitude": "-82.55",
        "Temperature (F)": "84.0",
        "Humidity (%)": "50.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "5.99"
    },
    {
        "City": "vicuna",
        "Country": "CL",
        "City ID": "8514.0",
        "Latitude": "-30.03",
        "Longitude": "-70.71",
        "Temperature (F)": "59.0",
        "Humidity (%)": "72.0",
        "Cloudiness (%)": "100.0",
        "Wind Speed (mph)": "12.75"
    },
    {
        "City": "barcelos",
        "Country": "PT",
        "City ID": "6900.0",
        "Latitude": "41.54",
        "Longitude": "-8.62",
        "Temperature (F)": "70.0",
        "Humidity (%)": "82.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "8.05"
    },
    {
        "City": "alofi",
        "Country": "NU",
        "City ID": "7306.0",
        "Latitude": "-19.06",
        "Longitude": "-169.92",
        "Temperature (F)": "66.2",
        "Humidity (%)": "93.0",
        "Cloudiness (%)": "63.0",
        "Wind Speed (mph)": "1.12"
    },
    {
        "City": "batman",
        "Country": "TR",
        "City ID": "6996.0",
        "Latitude": "37.89",
        "Longitude": "41.13",
        "Temperature (F)": "78.8",
        "Humidity (%)": "57.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "2.24"
    },
    {
        "City": "acapulco",
        "Country": "MX",
        "City ID": "7103.0",
        "Latitude": "16.86",
        "Longitude": "-99.89",
        "Temperature (F)": "91.4",
        "Humidity (%)": "49.0",
        "Cloudiness (%)": "90.0",
        "Wind Speed (mph)": "21.92"
    },
    {
        "City": "saint anthony",
        "Country": "US",
        "City ID": "4900.0",
        "Latitude": "45.02",
        "Longitude": "-93.22",
        "Temperature (F)": "82.0",
        "Humidity (%)": "65.0",
        "Cloudiness (%)": "7.0",
        "Wind Speed (mph)": "6.93"
    },
    {
        "City": "east wenatchee bench",
        "Country": "US",
        "City ID": "3917.0",
        "Latitude": "47.43",
        "Longitude": "-120.28",
        "Temperature (F)": "87.01",
        "Humidity (%)": "22.0",
        "Cloudiness (%)": "1.0",
        "Wind Speed (mph)": "17.22"
    },
    {
        "City": "maneromango",
        "Country": "TZ",
        "City ID": "2635.0",
        "Latitude": "-7.2",
        "Longitude": "38.78",
        "Temperature (F)": "75.2",
        "Humidity (%)": "83.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "5.7"
    },
    {
        "City": "kashirskoye",
        "Country": "RU",
        "City ID": "9034.0",
        "Latitude": "51.42",
        "Longitude": "39.61",
        "Temperature (F)": "66.2",
        "Humidity (%)": "55.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "4.47"
    },
    {
        "City": "raudeberg",
        "Country": "NO",
        "City ID": "1616.0",
        "Latitude": "61.99",
        "Longitude": "5.14",
        "Temperature (F)": "78.8",
        "Humidity (%)": "44.0",
        "Cloudiness (%)": "0.0",
        "Wind Speed (mph)": "11.41"
    },
    {
        "City": "saginaw",
        "Country": "US",
        "City ID": "4459.0",
        "Latitude": "43.33",
        "Longitude": "-84.03",
        "Temperature (F)": "82.4",
        "Humidity (%)": "39.0",
        "Cloudiness (%)": "1.0",
        "Wind Speed (mph)": "13.87"
    },
    {
        "City": "road town",
        "Country": "VG",
        "City ID": "8799.0",
        "Latitude": "18.42",
        "Longitude": "-64.62",
        "Temperature (F)": "88.0",
        "Humidity (%)": "70.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "13.87"
    },
    {
        "City": "florida",
        "Country": "US",
        "City ID": "3612.0",
        "Latitude": "28.75",
        "Longitude": "-82.5",
        "Temperature (F)": "100.99",
        "Humidity (%)": "41.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "4.7"
    },
    {
        "City": "tondano",
        "Country": "ID",
        "City ID": "9356.0",
        "Latitude": "1.3",
        "Longitude": "124.91",
        "Temperature (F)": "75.2",
        "Humidity (%)": "100.0",
        "Cloudiness (%)": "40.0",
        "Wind Speed (mph)": "3.13"
    },
    {
        "City": "bamako",
        "Country": "ML",
        "City ID": "2354.0",
        "Latitude": "12.65",
        "Longitude": "-8.0",
        "Temperature (F)": "96.8",
        "Humidity (%)": "41.0",
        "Cloudiness (%)": "20.0",
        "Wind Speed (mph)": "5.82"
    }
]